"""empty message

Revision ID: 02aa18092278
Revises: 6ffb8cc3d897
Create Date: 2021-03-10 18:02:18.496064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aa18092278'
down_revision = '6ffb8cc3d897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_restaurant', sa.Column('image', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User_restaurant', 'image')
    # ### end Alembic commands ###
