"""empty message

Revision ID: 6b2fdfa94656
Revises: 02aa18092278
Create Date: 2021-03-10 18:26:27.700544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2fdfa94656'
down_revision = '02aa18092278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_client', sa.Column('passwordd', sa.String(length=255), nullable=False))
    op.drop_column('User_client', 'password')
    op.add_column('User_restaurant', sa.Column('passwordd', sa.String(length=255), nullable=False))
    op.drop_column('User_restaurant', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_restaurant', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('User_restaurant', 'passwordd')
    op.add_column('User_client', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('User_client', 'passwordd')
    # ### end Alembic commands ###
