"""empty message

Revision ID: c88e15df0190
Revises: 6b2fdfa94656
Create Date: 2021-03-10 18:26:51.887743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88e15df0190'
down_revision = '6b2fdfa94656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_client', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('User_client', 'passwordd')
    op.add_column('User_restaurant', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('User_restaurant', 'passwordd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_restaurant', sa.Column('passwordd', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('User_restaurant', 'password')
    op.add_column('User_client', sa.Column('passwordd', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('User_client', 'password')
    # ### end Alembic commands ###
