"""empty message

Revision ID: cd54e9d2fb1c
Revises: 0361fefb166d
Create Date: 2021-03-11 16:55:16.949237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd54e9d2fb1c'
down_revision = '0361fefb166d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_restaurant', sa.Column('image_urll', sa.String(length=250), nullable=True))
    op.drop_column('User_restaurant', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_restaurant', sa.Column('image_url', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('User_restaurant', 'image_urll')
    # ### end Alembic commands ###
